services:
  eia_webserver:
    container_name: eia_webserver
    build: .
    ports: 
      - "${FLASK_PORT:-5000}:5000" # Host:Container
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=${FLASK_ENV:-production}
    env_file:
      - .env   
